//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaBB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Film = new HashSet<Film>();
        }
    
        public int id { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string email { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual ICollection<Film> Film { get; set; }
        public virtual Role Role { get; set; }
    }
}
